services:
  postgres:
    image: postgres:17-alpine
    container_name: mecafix-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mecafix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - mecafix-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: mecafix-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mecafix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

volumes:
  mecafix-data:
